name: asn-web

services:
  app:
    image: asn-web-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: asn-web-app
    ports:
      - "8000:8000"
    restart: unless-stopped
